# This file is auto-generated by nixos-generate-config during installation.
# Run: nixos-generate-config --root /mnt
# Then copy /mnt/etc/nixos/hardware-configuration.nix to this location.
{
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };
  swapDevices = [{ device = "/dev/disk/by-label/swap"; }];
}
