require("bqf").setup({
  auto_enable = true,
  preview = {
    auto_preview = true,
    win_height = 12,
    win_vheight = 12,
    delay_syntax = 80,
    border = "rounded",
  },
  func_map = {
    open = "<CR>",
    openc = "o",
    drop = "O",
    tabdrop = "<C-t>",
    tab = "t",
    vsplit = "v",
    split = "s",
    prevfile = "<C-p>",
    nextfile = "<C-n>",
    prevhist = "<",
    nexthist = ">",
    pscrollup = "<C-b>",
    pscrolldown = "<C-f>",
    ptogglemode = "z,",
    ptoggleitem = "p",
    ptoggleauto = "P",
    fzffilter = "zf",
    filter = "zn",
    filterr = "zr",
    togglepos = "\\t",
  },
})
